version: '3.8'

services:
  webapi:
    build: .
    ports:
      - "4041:4041"  # Map container port 80 to host port 4041
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  dummy-service:  # Optional second container (for example purpose)
    image: nginx
    ports:
      - "4042:80"
